In [1]:
#Importamos el modulo de Google Drive
#from google.colab import drive
#MOntamos la carpeta content de Drive
#drive.mount("/content/drive")
#Asignamos la ruta donde se encuentra nuestro dataset
#archivo="/content/drive/MyDrive/data/Iris.csv"
archivo = "C:/Users/TOSHIBA/Desktop/INF - 354/Segundo Parcial/P1/Iris.csv"

#importamos la libreria random
import random
#importamos la libreria csv
import csv
#Importaremos pandas solamente para observar el dataset
import pandas as pd
#Importaremos la libreria numpy
import numpy as np
#importamos la libreria math
import math
#Importamos la libreria matplotlib para graficar
import matplotlib.pyplot as plt
#Importamos la libreria de sklearn para hacer el train test split
from sklearn.model_selection import train_test_split
#Utilizaremos la libreria para convertir a one hot encoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv(archivo)
#Mostramos el dataset Iris
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
#funcion para obtener X y y
def obtenerDatos(ruta):
  #X tendra los registros menos la columna de la variable objetivo similar a iris.data
  X = []
  #Almacenara los registros de los tipos de flor similar a iris.target
  y = []
  with open(ruta, 'r', newline='') as dataset:
    lector_csv = csv.reader(dataset)

    # Leemos cada fila del archivo CSV
    for fila in lector_csv:
        # Agregamos todas las columnas excepto la última a X
        X.append(fila[1:-1])
        # Agregamos la última columna a y
        y.append(fila[-1])
    #Eliminamos las cabeceras y convertimos los datos a float
    X = [[float(elemento) for elemento in fila] for fila in X[1:]]
    #Eliminamos las cabeceras
    y = y[1:]
    #vamos a cambiar la etiquetas al estandar label encoder
    le = []
    for i in range(len(y)):
      if(y[i] == "Iris-setosa"):
        le.append(0)
      elif(y[i] == "Iris-virginica"):
        le.append(1)
      elif(y[i] == "Iris-versicolor"):
        le.append(2)
    return X, le

#En X almancenaremos los registros del dataset
#en y almacenaremos la variable objetivo del dataset
X,y =  obtenerDatos(archivo)
#Mostramos X
print(X)
#Mostramos y
print(y)

[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [4.6, 3.4, 1.4, 0.3], [5.0, 3.4, 1.5, 0.2], [4.4, 2.9, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.4, 3.7, 1.5, 0.2], [4.8, 3.4, 1.6, 0.2], [4.8, 3.0, 1.4, 0.1], [4.3, 3.0, 1.1, 0.1], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [4.6, 3.6, 1.0, 0.2], [5.1, 3.3, 1.7, 0.5], [4.8, 3.4, 1.9, 0.2], [5.0, 3.0, 1.6, 0.2], [5.0, 3.4, 1.6, 0.4], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [4.7, 3.2, 1.6, 0.2], [4.8, 3.1, 1.6, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.0, 3.2, 1.2, 0.2], [5.5, 3.5, 1.3, 0.2], [4.9, 3.1, 1.5, 0.1], [4.4, 3.0, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.0, 3.5, 1.3, 0.3], [4.5, 2.3, 1.3, 0.3], [4.4, 3.2, 1.3, 0.2], [5.0, 3.5, 1.6, 0.6], [5.1, 3.8, 1.9, 0.4], [4.8, 3.0

In [4]:
#definimos la funcion estandarizar para estandarizar los registros
def estandarizar(X):
    #obentemos el numero de filas de los registros
    filas = len(X)
    #Obtenemos el numero de columnas de los registros
    columnas = len(X[0])
    #array para almacenar las medias de cada columna
    array_medias = [] 
    #iteramos  sobre cada columna
    for i in range(columnas):
        #variable para sumar las columnas
        suma = 0  
        #iteramos las filas de la matriz
        for j in range(filas):
            suma += X[j][i]   
        #calculamos la media
        media_columna = suma / filas
        #añadimos al array de medias
        array_medias.append(media_columna)
    #halamos la desviación estandar 
    desviaciones_estandar = [math.sqrt(sum((X[j][i] - array_medias[i]) ** 2 for j in range(filas)) / filas) for i in range(columnas)]
    #realizamos la estandarizacion
    X_estandarizado = [[(X[j][i] - array_medias[i]) / desviaciones_estandar[i] for i in range(columnas)] for j in range(filas)]
    #retornamos X estandarizado
    return X_estandarizado


def convertir_a_one_hot(array):
  # Reshape el array a una matriz de una sola columna
  reshape = np.array(array).reshape(-1, 1)
  # Crear una instancia del OneHotEncoder
  encoder = OneHotEncoder(sparse=False, categories='auto')
  # Ajustar y transformar el array
  array_one_hot = encoder.fit_transform(reshape)
  return array_one_hot

In [5]:
X = estandarizar(X)
y = convertir_a_one_hot(y)
print(X)
print(y)

[[-0.9006811702978099, 1.0320572244889554, -1.3412724047598341, -1.3129767272601454], [-1.1430169111851116, -0.12495760117131036, -1.3412724047598341, -1.3129767272601454], [-1.3853526520724144, 0.3378483290927964, -1.3981381087490865, -1.3129767272601454], [-1.5065205225160663, 0.106445363960743, -1.2844067007705817, -1.3129767272601454], [-1.0218490407414607, 1.2634601896210087, -1.3412724047598341, -1.3129767272601454], [-0.5371775589668552, 1.9576690850171679, -1.170675292792077, -1.050030787221398], [-1.5065205225160663, 0.800654259356902, -1.3412724047598341, -1.1815037572407716], [-1.0218490407414607, 0.800654259356902, -1.2844067007705817, -1.3129767272601454], [-1.748856263403368, -0.3563605663033637, -1.3412724047598341, -1.3129767272601454], [-1.1430169111851116, 0.106445363960743, -1.2844067007705817, -1.4444496972795189], [-0.5371775589668552, 1.4948631547530622, -1.2844067007705817, -1.3129767272601454], [-1.2641847816287635, 0.800654259356902, -1.2275409967813293, -1.312

C:\Users\TOSHIBA\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [6]:
#Definimos la proporcion del 80% para entrenamiento
proporcion_entrenamiento = 0.8
#Definimos la proporcion del 20% para prueba
proporcion_prueba = 0.2
#Cantidad de registros del dataset
muestras = 150
#definimos los indices
indices = list(range(muestras))
#mezclamos los indices dentro de la lista
random.shuffle(indices)
#cantidad de muestras para train
num_train = int(muestras * proporcion_entrenamiento)
#cantidad de muestras para test
num_test = int(muestras * proporcion_prueba)
#indices para entrenamieto
train_indices = indices[:num_train]
#indices para prueba
test_indices = indices[:num_test]
#Obtenemos los datos de entrenamiento y de prueba para X y y
X_train = [X[i] for i in train_indices]
y_train = [y[i] for i in train_indices]
X_test = [X[i] for i in test_indices]
y_test = [y[i] for i in test_indices]
print("X_train")
X_train = np.array(X_train)
print(X_train)
print("y_train")
y_train = np.array(y_train)
print(y_train)
print("X_test")
X_test = np.array(X_test)
print(X_test)
print("y_test")
y_test = np.array(y_test)
print(y_test)

X_train
[[ 5.53333275e-01 -1.74477836e+00  3.64698715e-01  1.33225943e-01]
 [-5.37177559e-01  1.49486315e+00 -1.28440670e+00 -1.31297673e+00]
 [ 7.95669016e-01  3.37848329e-01  7.62758643e-01  1.05353673e+00]
 [-1.73673948e-01 -1.28197243e+00  7.05892939e-01  1.05353673e+00]
 [-1.02184904e+00  1.26346019e+00 -1.34127240e+00 -1.31297673e+00]
 [-1.73673948e-01 -5.87763531e-01  1.94101603e-01  1.33225943e-01]
 [-4.16009689e-01 -1.05056946e+00  3.64698715e-01  1.75297293e-03]
 [-1.26418478e+00 -1.24957601e-01 -1.34127240e+00 -1.44444970e+00]
 [-1.73673948e-01  1.72626612e+00 -1.17067529e+00 -1.18150376e+00]
 [-2.94841818e-01 -1.28197243e+00  8.03701950e-02 -1.29719997e-01]
 [-5.25060772e-02  2.18907205e+00 -1.45500381e+00 -1.31297673e+00]
 [-5.37177559e-01 -1.24957601e-01  4.21564419e-01  3.96171883e-01]
 [ 5.53333275e-01  5.69251294e-01  1.27454998e+00  1.71090158e+00]
 [-1.50652052e+00  1.06445364e-01 -1.28440670e+00 -1.31297673e+00]
 [ 1.40150837e+00  3.37848329e-01  5.35295827e-01  2.6

In [7]:
#Definimos los pesos que tendra la red neuronal
#Pesos
w0 = [[random.uniform(-1, 1) for _ in range(4)] for _ in range(3)]
w1 = [[random.uniform(-1, 1) for _ in range(3)] for _ in range(3)]
#Definimos la tasa de aprendizaje
tasa_aprendizaje = 0.1
#Creamos un array donde se almacenaran los valores de error del entrenamiento
errors = []
accuracy = []

In [8]:
#definimos la funcion de activación ReLU
def relu(x):
    return max(0, x)

#definimos la funcion de activacion Softmax que nos servira para realizar la clasificacion ya que la salida de esta se interpretara como probabilidades de las clases
def softmax(x):
    exp_values = [math.exp(i - max(x)) for i in x]
    sum_exp_values = sum(exp_values)
    return [i / sum_exp_values for i in exp_values]

In [9]:
#Declaramos el numero de epocas
epocas = 1000
for epocas in range(epocas):
    #Variable para calcular el error promedio
    error_promedio = 0
    #ingresamos fila por fila
    for i in range(len(X_train)):
        #datos de entrada
        capa_entrada = X_train[i]
        #Primera capa efectuamos el producto punto entre los valores de entrada y el peso w0
        #Ademas se aplica la funcion de activacion ReLU
        primera_capa = [relu(sum([capa_entrada[p] * w0[k][p] for p in range(4)])) for k in range(3)]
        #Segunda capa efectuamos el producto punto entre la salida de la anterior capa y el peso w1
        #Ademas se aplica la funcion de activacion softmax  
        segunda_capa = softmax([sum([primera_capa[p] * w1[k][p] for p in range(3)]) for k in range(3)])
        #hallamos el error cuadratico medio
        error = sum([(y_train[i][k] - segunda_capa[k]) ** 2 for k in range(3)]) / 2
        #sumamos al error promedio
        error_promedio += error
        #realizaremos el algoritmo de Backpropagation
        for k in range(3):
            for p in range(4):
                sumatoria_oculta = sum([(y_train[i][l] - segunda_capa[l]) * w1[l][k] for l in range(3)])
                w0[k][p] += tasa_aprendizaje * sumatoria_oculta * capa_entrada[p]
        for k in range(3):
            for p in range(3):
                w1[k][p] += tasa_aprendizaje * (y_train[i][k] - segunda_capa[k]) * primera_capa[p]
    #calculamos el error promedio
    error_promedio /= len(X_train)
    print(f"Epoca: {epocas} Error promedio: {error_promedio}, Precisión promedio: {(1 - error_promedio) * 100:.2f}%")


Epoca: 0 Error promedio: 0.20998922923455973, Precisión promedio: 79.00%
Epoca: 1 Error promedio: 0.18404079044405805, Precisión promedio: 81.60%
Epoca: 2 Error promedio: 0.18298645139385974, Precisión promedio: 81.70%
Epoca: 3 Error promedio: 0.19000818101346875, Precisión promedio: 81.00%
Epoca: 4 Error promedio: 0.18971677662767075, Precisión promedio: 81.03%
Epoca: 5 Error promedio: 0.16061311826176453, Precisión promedio: 83.94%
Epoca: 6 Error promedio: 0.166703160392315, Precisión promedio: 83.33%
Epoca: 7 Error promedio: 0.23918400433344558, Precisión promedio: 76.08%
Epoca: 8 Error promedio: 0.18820789312223907, Precisión promedio: 81.18%
Epoca: 9 Error promedio: 0.2227410095071179, Precisión promedio: 77.73%
Epoca: 10 Error promedio: 0.1614090225946728, Precisión promedio: 83.86%
Epoca: 11 Error promedio: 0.15344983254867456, Precisión promedio: 84.66%
Epoca: 12 Error promedio: 0.21418169569679935, Precisión promedio: 78.58%
Epoca: 13 Error promedio: 0.16509561893590224, Preci

In [10]:
#Realizaremos las predicciones con el conjuto X_test
predicciones = []
#iteraremos sobre el conjunto de prueba
for i in range(len(X_test)):
    #ingresaremos X_Test
    capa_entrada = X_test[i]
    #calcularemos los valores para la primera capa
    primera_capa = [relu(sum([capa_entrada[p] * w0[k][p] for p in range(4)])) for k in range(3)]
    #calcularemos los valores para la segunda capa
    segunda_capa = softmax([sum([primera_capa[p] * w1[k][p] for p in range(3)]) for k in range(3)])
    #las predicciones realizadas las almacenaremos en este array
    predicciones.append(segunda_capa)

#mostraremos las predicciones
for i in range(len(X_test)):
    print(f"Predicción para entrada: {X_test[i]} valor real {y_test[i]} valor predecido  {predicciones[i]}")

Predicción para entrada: [ 0.55333328 -1.74477836  0.36469871  0.13322594] valor real [0. 0. 1.] valor predecido  [6.843030943647933e-28, 0.08135842199677981, 0.9186415780032201]
Predicción para entrada: [-0.53717756  1.49486315 -1.2844067  -1.31297673] valor real [1. 0. 0.] valor predecido  [1.0, 0.0, 0.0]
Predicción para entrada: [0.79566902 0.33784833 0.76275864 1.05353673] valor real [0. 1. 0.] valor predecido  [3.7614821134550174e-33, 0.9775271352081397, 0.022472864791860146]
Predicción para entrada: [-0.17367395 -1.28197243  0.70589294  1.05353673] valor real [0. 1. 0.] valor predecido  [1.1280289098552199e-29, 0.966672393187596, 0.033327606812403966]
Predicción para entrada: [-1.02184904  1.26346019 -1.3412724  -1.31297673] valor real [1. 0. 0.] valor predecido  [1.0, 0.0, 0.0]
Predicción para entrada: [-0.17367395 -0.58776353  0.1941016   0.13322594] valor real [0. 0. 1.] valor predecido  [9.454442644059337e-08, 0.3636811085728205, 0.6363187968827531]
Predicción para entrada: [

In [11]:
#Calcularemos la precision del modelo
correctas = 0
#iteraremos sobre X_test
for i in range(len(X_test)):
    capa_entrada = X_test[i]
    primera_capa = [relu(sum([capa_entrada[p] * w0[k][p] for p in range(4)])) for k in range(3)]
    segunda_capa = softmax([sum([primera_capa[p] * w1[k][p] for p in range(3)]) for k in range(3)])
    #obtendremos la clase predicha
    clase_predicha = np.argmax(segunda_capa)
    #compararemos con la clase verdadera
    if clase_predicha == np.argmax(y_test[i]):
        correctas += 1
#calculamos la precision
precision = correctas / len(X_test)
#mostramos la precision
print(f"Precisión del modelo en el conjunto de prueba: {precision*100}%")


Precisión del modelo en el conjunto de prueba: 76.66666666666667%
